name: chainlib

on:
  push:
    branches: main
  pull_request:
    paths:
      - "cosmos-sdk-proto/**"
      - "cosmos-tx/**"
      - "Cargo.*"

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0 # MSRV
          components: rustfmt
          override: true
          profile: minimal
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.49.0 # MSRV
          components: clippy
          override: true
          profile: minimal
      - run: cargo clippy --all -- -D warnings # TODO: --all-features

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.49.0 # MSRV
          - stable
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --target ${{ matrix.target }} --release

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.49.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test --release